# Generated by Django 4.0.6 on 2022-07-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubi_cordenada', models.CharField(max_length=100)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='paquete.paquete')),
            ],
        ),
    ]
