# Generated by Django 4.0.6 on 2022-07-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='repartiidor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='user.extencion'),
            preserve_default=False,
        ),
    ]
