# Generated by Django 4.0.6 on 2022-07-28 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0002_paquete_repartiidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='repartiidor',
            new_name='repartidor',
        ),
    ]
