# Generated by Django 4.0.6 on 2022-08-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0006_paquete_paq_confirmacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='paq_fechaConfirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='paq_fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='paq_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquete/'),
        ),
    ]
