# Generated by Django 4.0.6 on 2022-08-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0007_alter_paquete_paq_fechaconfirmacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='paq_horaConfirmacion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='paq_horaCreacion',
            field=models.TimeField(auto_now_add=True, default='19:45:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paquete',
            name='paq_fechaConfirmacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='paq_fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
