# Generated by Django 4.0.6 on 2023-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0008_paquete_paq_horaconfirmacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='paq_confirmacion',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='paq_numero',
            field=models.CharField(max_length=13),
        ),
    ]
