# Generated by Django 4.0.6 on 2023-06-14 21:00

from django.db import migrations, models
import django.db.models.deletion
from paquete import data

class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0009_alter_paquete_paq_confirmacion_and_more'),
    ]

    def importarTipoPaquete(apps, schema_editor):
        dta = data.importDataValue("tipoPaquete.csv")
        print(dta)
        tipoPaquete = apps.get_model('paquete', 'tipoPaquete')
        for item in dta:
            tipoPaquete.objects.create(**item)

    operations = [
        migrations.CreateModel(
            name='tipoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=5)),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'tipoPaquete',
                'verbose_name_plural': 'tipoPaquetes',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='paq_peso',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='paq_precio',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='paq_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='paquete.tipopaquete'),
        ),
        migrations.RunPython(importarTipoPaquete),
    ]
