# Generated by Django 4.0.6 on 2023-07-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0010_tipopaquete_paquete_paq_peso_paquete_paq_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='paq_barCode',
            field=models.ImageField(blank=True, null=True, upload_to='barCode/'),
        ),
    ]
