# Generated by Django 4.0.6 on 2023-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0011_paquete_paq_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='paq_active',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
