# Generated by Django 4.0.6 on 2023-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0012_paquete_paq_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='paq_active',
            field=models.IntegerField(default=1),
        ),
    ]
