# Generated by Django 4.0.6 on 2023-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_extencion_cedula_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extencion',
            name='imagen',
            field=models.ImageField(blank=True, default='user/default_user.png', null=True, upload_to='user/'),
        ),
    ]
